/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class mmlvkk_Test */

#ifndef _Included_mmlvkk_Test
#define _Included_mmlvkk_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmlvkk_Test
 * Method:    nativeHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mmlvkk_Test_nativeHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
